name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GO111MODULE: on
  GOOS: darwin
  CGO_ENABLED: 1
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: output os version
        run: |
          sw_vers
      - name: Build for macos-latest
        run: |
          echo "===build amd64 release"
          export GOARCH=amd64
          go build -o dist/apixia-macos-amd64
          unset GOARCH
          echo "===build arm64 release"
          go build -o dist/apixia-macos-arm64
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m "Add built artifact for ${{ matrix.os }}"
          git push
