name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GO111MODULE: on
  GOOS: darwin
  CGO_ENABLED: 1
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - name: output os version
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            sw_vers
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            ver
          fi
      - name: Build for macos-latest
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "===build amd64 release"
            export GOARCH=amd64
            go build -o dist/apixia-macos-amd64
            unset GOARCH
            echo "===build arm64 release"
            go build -o dist/apixia-macos-arm64
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-${{ matrix.os }}
          path: |
            myapp-macos
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "===build windows amd64 release"
          go build -ldflags -H=windowsgui -o dist/apixia-windows-amd64.exe
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/
          git commit -m "Add built artifact for ${{ matrix.os }}"
          git push
